# Generated by Django 4.2.2 on 2023-07-10 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.URLField(blank=True, null=True, verbose_name='Беседа вк')),
                ('status', models.CharField(choices=[('MN', 'Main'), ('SP', 'Special'), ('FR', 'Free')], default='MN', max_length=2, verbose_name='Тип курса')),
                ('image', models.ImageField(upload_to='courses/', verbose_name='Картинка')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curator_courses', to=settings.AUTH_USER_MODEL, verbose_name='Куратор')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('code_of_translation', models.CharField(max_length=100, verbose_name='Код трансляции')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webinars', to='course.course', verbose_name='Курс')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Условие текстом')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='tasks/', verbose_name='Условие картинкой')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='course.webinar', verbose_name='Вебинар')),
            ],
        ),
        migrations.CreateModel(
            name='FileOfWebinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_of_webinar', models.FileField(upload_to='files/', verbose_name='Файл')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='course.webinar', verbose_name='Вебинар')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course.exam', verbose_name='Экзамен'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_courses', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
    ]
