# Generated by Django 4.2.2 on 2023-07-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Экзамен', 'verbose_name_plural': 'Экзамены'},
        ),
        migrations.AlterModelOptions(
            name='fileofwebinar',
            options={'verbose_name': 'Файл для вебинара', 'verbose_name_plural': 'Файлы для вебинаров'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='webinar',
            options={'verbose_name': 'Вебинар', 'verbose_name_plural': 'Вебинары'},
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
