# Generated by Django 4.2.2 on 2023-07-12 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_curator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curator',
            options={'verbose_name': 'Куратор', 'verbose_name_plural': 'Кураторы'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='exam',
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='course.exam', verbose_name='Экзамен')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course.subject', verbose_name='Предмет'),
        ),
    ]
