# Generated by Django 4.2.2 on 2023-07-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_curator_options_remove_course_exam_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='full_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Цена за курс до конца года'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Цена за месяц'),
        ),
    ]
