# Generated by Django 4.2.2 on 2023-07-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileofwebinar',
            name='title',
            field=models.CharField(default=None, max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
