# Generated by Django 4.2.2 on 2023-08-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_rename_curator_curator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='checkbox_answer_1',
            field=models.TextField(blank=True, null=True, verbose_name='Множественный ответ 1'),
        ),
        migrations.AddField(
            model_name='task',
            name='checkbox_answer_2',
            field=models.TextField(blank=True, null=True, verbose_name='Множественный ответ 2'),
        ),
        migrations.AddField(
            model_name='task',
            name='checkbox_answer_3',
            field=models.TextField(blank=True, null=True, verbose_name='Множественный ответ 3'),
        ),
        migrations.AddField(
            model_name='task',
            name='checkbox_answer_4',
            field=models.TextField(blank=True, null=True, verbose_name='Множественный ответ 4'),
        ),
        migrations.AddField(
            model_name='task',
            name='checkbox_answer_5',
            field=models.TextField(blank=True, null=True, verbose_name='Множественный ответ 5'),
        ),
        migrations.AddField(
            model_name='task',
            name='checkbox_right_answer_1',
            field=models.BooleanField(default=False, verbose_name='Является ли ответ 1 верным?'),
        ),
        migrations.AddField(
            model_name='task',
            name='checkbox_right_answer_2',
            field=models.BooleanField(default=False, verbose_name='Является ли ответ 2 верным?'),
        ),
        migrations.AddField(
            model_name='task',
            name='checkbox_right_answer_3',
            field=models.BooleanField(default=False, verbose_name='Является ли ответ 3 верным?'),
        ),
        migrations.AddField(
            model_name='task',
            name='checkbox_right_answer_4',
            field=models.BooleanField(default=False, verbose_name='Является ли ответ 4 верным?'),
        ),
        migrations.AddField(
            model_name='task',
            name='checkbox_right_answer_5',
            field=models.BooleanField(default=False, verbose_name='Является ли ответ 5 верным?'),
        ),
        migrations.AddField(
            model_name='task',
            name='solution',
            field=models.TextField(blank=True, null=True, verbose_name='Решение текстом'),
        ),
        migrations.AddField(
            model_name='task',
            name='solution_image',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/solution/', verbose_name='Решение картинкой'),
        ),
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ полем ввода'),
        ),
    ]
