# Generated by Django 4.2.2 on 2023-07-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ пользователя', 'verbose_name_plural': 'Заказы пользователей'},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='update_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата продления курса'),
        ),
    ]
