# Generated by Django 4.2.2 on 2023-07-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_alter_orderitem_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='update_date',
            field=models.DateField(verbose_name='Дата продления курса'),
        ),
    ]
