# Generated by Django 4.2.2 on 2023-07-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_active_alter_orderitem_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='create_date',
            field=models.DateField(verbose_name='Дата покупки курса'),
        ),
    ]
