# Generated by Django 4.2.2 on 2023-07-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderitem_options_alter_orderitem_create_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
