# Generated by Django 4.2.2 on 2023-07-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
    ]
