# Generated by Django 4.2.2 on 2023-07-23 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_rename_curator_curator_user'),
        ('order', '0010_rename_ordercourse_confirmedcourse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmedcourse',
            options={'verbose_name': 'Купленный курс', 'verbose_name_plural': 'Купленные курсы'},
        ),
        migrations.AlterField(
            model_name='confirmedcourse',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curator_orders', to='course.curator', verbose_name='Куратор'),
        ),
        migrations.AlterField(
            model_name='confirmedcourse',
            name='price_with_discount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='Куплен по цене'),
        ),
    ]
