# Generated by Django 4.2.2 on 2023-07-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_confirmedcourse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedcourse',
            name='price_with_discount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='Цена по скидке\n(если есть)'),
        ),
    ]
