# Generated by Django 4.2.2 on 2023-08-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_confirmedcourse_price_with_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedcourse',
            name='price_with_discount',
        ),
        migrations.AddField(
            model_name='confirmedcourse',
            name='result_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='Итоговая цена'),
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Оплачено в коп.'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Идентификатор сохраненной карты в системе банка'),
        ),
        migrations.AddField(
            model_name='order',
            name='error_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код ошибки (0=Успех)'),
        ),
        migrations.AddField(
            model_name='order',
            name='exp_date',
            field=models.TextField(blank=True, null=True, verbose_name='Срок действия карты MMYY'),
        ),
        migrations.AddField(
            model_name='order',
            name='pan',
            field=models.TextField(blank=True, null=True, verbose_name='Замаскированный номер карты/Замаскированный номер телефона'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Идентификатор платежа в системе банка'),
        ),
        migrations.AddField(
            model_name='order',
            name='rebill_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Идентификатор автоплатежа'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='order',
            name='terninal_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.TextField(blank=True, null=True, verbose_name='Токен (См. Подпись запроса)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='result_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='Полная цена'),
        ),
    ]
