# Generated by Django 4.2.2 on 2023-08-06 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_remove_order_rebill_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='terninal_key',
            new_name='terminal_key',
        ),
    ]
