# Generated by Django 4.2.2 on 2023-08-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_rename_terninal_key_order_terminal_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор платежа в системе банка'),
        ),
    ]
